version: '3.7'

services:
  php:
    build: ./docker
    container_name: LLEMP_php
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - './src:/var/www'
      - './etc/profile.d/php7.sh:/var/etc/profile.d/php7.sh'
      - './etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 9001:80
